backend:
  name: github
  repo: jeff397/Villers
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: test
    label: Test
    folder: src/data/test
    create: true
    format: json
    extension: json
    fields:
      - label: Titre
        name: title
        widget: string
